### ISSUE TITLE
변경된 views파일들에 라우팅 해결

### ISSUE THREAD

**Issue by flydog98** [seol11796/sub_weather#12]
현재 main branch에 routing문제가 있어서 router단에서 올바른 views 파일로 라우팅 되도록 수정해야 합니다.

**Comment by seol11796** [comment]
< views와 routes의 변수 설정 관련 > 
**[ routes/map.js ]**
router.get("/:stationName", async function (req, res) {
  complexityService.getComplexity(req.params.stationName);
  finedustService.getFinedust(req.params.stationName);

  res.render("maps/index", {
  //// 서비스에서 처리해서 라우트에서 넘겨준 것 여기서 보여주기 
    station_name:station_name,
    station_number:station_number, // ex) 2호선, 2 
  
    
    // *가장 혼잡한 시간* 
    // 상선
    geton_maxcpx : geton_maxcpx,
    getoff_maxcpx : getoff_maxcpx, 
    // 가장 한가한 시간
    // 하선
    geton_mincpx : geton_maxcpx,
    getoff_mincpx : getoff_mincpx,

    // *공기질*
    // 실제수치 
    pm : pm ,

    // *편의시설*
    // 물품보관함
    locker_location: locker_location ,
    // 주변 건물 
    nearby_building : nearby_building ,

    // S3를 통해 불러온 해당 지하철 역 이미지 
    subway_image : subway_image 



  });

**[ routes/station.js]**

router.get("/:stationName", async function (req, res) {
  complexityService.getComplexity(req.params.stationName);
  finedustService.getFinedust(req.params.stationName);



  res.render("stations/about", {
    
    // 서비스에서 처리해서 라우트에서 넘겨준 것 여기서 보여주기 
    station_name:station_name,
    station_number:station_number,

    // *혼잡도*
    // 혼잡도 계산 후 현재역 쾌적한 지 판단 
    complexity_state : complexity_state,
    

    // *공기질*
    // 실제수치에 따른 좋음,보통,나쁨 상태표시 
    dust_state : dust_state ,

    // *편의시설*
    // 물품보관함
    locker_location: locker_location ,
    // 주변 건물 
    nearby_building : nearby_building ,

  });
